name: Run Testes
run-name: On Push - Testes Run
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Testes"
# name: End-to-end tests 🧪
# on: [push]

# jobs:
#   e2e-tests:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2

#       - name: Setup Node.js
#         uses: actions/setup-node@v2
#         with:
#           node-version: "14"

#       - name: Install dependencies
#         run: npm ci

#       - name: Run e2e tests
#         run: npm test
